import type { IndicatorRule, LevelBandRule, RuleConflict, RuleSet, RuleSource } from '../types'

const GAZETTE_42496 = 'https://www.gov.za/documents/notices/broad-based-black-economic-empowerment-amendment-act-b-b-bbee-code-series-general'

const STATEMENT_000: RuleSource = {
  citation: 'Amended Code Series 000, Statement 000 (General Principles and the Generic Scorecard)',
  notice: 'GN 306 of 2019, Government Gazette 42496, 31 May 2019',
  url: 'https://www.gov.za/sites/default/files/gcis_document/201905/42496gen306.pdf',
  standing: 'gazetted',
}

const STATEMENT_100: RuleSource = {
  citation: 'Code Series 100, Statement 100 (Measurement of the Ownership Element)',
  notice: 'Amended Codes of Good Practice, Government Gazette 36928, 11 October 2013',
  url: GAZETTE_42496,
  standing: 'gazetted',
}

const STATEMENT_200: RuleSource = {
  citation: 'Code Series 200, Statement 200 (Measurement of the Management Control Element)',
  notice: 'Amended Codes of Good Practice, Government Gazette 36928, 11 October 2013',
  url: GAZETTE_42496,
  standing: 'gazetted',
}

const STATEMENT_300: RuleSource = {
  citation: 'Amended Code Series 300, Statement 300 (General Principles for Measuring Skills Development)',
  notice: 'GN 305 of 2019, Government Gazette 42496, 31 May 2019',
  url: 'https://www.gov.za/sites/default/files/gcis_document/201905/42496gen305.pdf',
  standing: 'gazetted',
}

const STATEMENT_400: RuleSource = {
  citation: 'Amended Code Series 400, Statement 400 (Enterprise and Supplier Development)',
  notice: 'GN 304 of 2019, Government Gazette 42496, 31 May 2019',
  url: GAZETTE_42496,
  standing: 'gazetted',
}

const STATEMENT_500: RuleSource = {
  citation: 'Code Series 500, Statement 500 (Measurement of the Socio-Economic Development Element)',
  notice: 'Amended Codes of Good Practice, Government Gazette 36928, 11 October 2013',
  url: GAZETTE_42496,
  standing: 'gazetted',
}

export const GENERIC_2019_LEVEL_BANDS: LevelBandRule[] = [
  { level: 'Level 1', min: 100, recognitionPercentage: 135 },
  { level: 'Level 2', min: 95, maxExclusive: 100, recognitionPercentage: 125 },
  { level: 'Level 3', min: 90, maxExclusive: 95, recognitionPercentage: 110 },
  { level: 'Level 4', min: 80, maxExclusive: 90, recognitionPercentage: 100 },
  { level: 'Level 5', min: 75, maxExclusive: 80, recognitionPercentage: 80 },
  { level: 'Level 6', min: 70, maxExclusive: 75, recognitionPercentage: 60 },
  { level: 'Level 7', min: 55, maxExclusive: 70, recognitionPercentage: 50 },
  { level: 'Level 8', min: 40, maxExclusive: 55, recognitionPercentage: 10 },
  { level: 'Non-compliant', min: -Infinity, maxExclusive: 40, recognitionPercentage: 0 },
]

const OWNERSHIP_INDICATORS: IndicatorRule[] = [
  {
    key: 'ownership.voting_rights.black_people',
    elementKey: 'ownership',
    displayName: 'Exercisable voting rights of black people',
    target: 0.25,
    targetLabel: '25% + 1 vote',
    basePoints: 4,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Exercisable voting rights held by black people',
    denominatorLabel: 'Total exercisable voting rights',
    plusOneVote: true,
    source: STATEMENT_100,
    notes:
      'Where exact vote counts are supplied the effective target is (25% of total votes + 1) / total votes. Without vote counts the engine falls back to a documented 25.1% approximation and flags it.',
  },
  {
    key: 'ownership.voting_rights.black_women',
    elementKey: 'ownership',
    displayName: 'Exercisable voting rights of black women',
    target: 0.1,
    targetLabel: '10%',
    basePoints: 2,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Exercisable voting rights held by black women',
    denominatorLabel: 'Total exercisable voting rights',
    source: STATEMENT_100,
  },
  {
    key: 'ownership.economic_interest.black_people',
    elementKey: 'ownership',
    displayName: 'Economic interest of black people',
    target: 0.25,
    targetLabel: '25%',
    basePoints: 4,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Economic interest held by black people',
    denominatorLabel: 'Total economic interest',
    source: STATEMENT_100,
  },
  {
    key: 'ownership.economic_interest.black_women',
    elementKey: 'ownership',
    displayName: 'Economic interest of black women',
    target: 0.1,
    targetLabel: '10%',
    basePoints: 2,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Economic interest held by black women',
    denominatorLabel: 'Total economic interest',
    source: STATEMENT_100,
  },
  {
    key: 'ownership.economic_interest.designated_groups',
    elementKey: 'ownership',
    displayName: 'Economic interest of black designated groups, ESOPs, co-operatives and BBOS',
    target: 0.03,
    targetLabel: '3%',
    basePoints: 3,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Economic interest held by black designated groups / ESOP / BBOS',
    denominatorLabel: 'Total economic interest',
    source: STATEMENT_100,
  },
  {
    key: 'ownership.new_entrants',
    elementKey: 'ownership',
    displayName: 'Economic interest of black new entrants',
    target: 0.02,
    targetLabel: '2%',
    basePoints: 2,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Economic interest held by black new entrants',
    denominatorLabel: 'Total economic interest',
    source: STATEMENT_100,
  },
  {
    key: 'ownership.net_value',
    elementKey: 'ownership',
    displayName: 'Net value',
    target: 0.25,
    targetLabel: '25%',
    basePoints: 8,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Net value percentage attributable to black people',
    denominatorLabel: 'Target net value under Annexe 100(E) time-based graduation factor',
    source: STATEMENT_100,
    notes:
      'Net value must be supplied as a verified result. This release does not model the underlying transaction, deemed-value or debt calculation.',
  },
]

const MANAGEMENT_CONTROL_INDICATORS: IndicatorRule[] = [
  {
    key: 'management_control.board.black_people',
    elementKey: 'management_control',
    displayName: 'Exercisable voting rights of black board members',
    target: 0.5,
    targetLabel: '50%',
    basePoints: 2,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Black board members',
    denominatorLabel: 'All board members',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.board.black_women',
    elementKey: 'management_control',
    displayName: 'Exercisable voting rights of black female board members',
    target: 0.25,
    targetLabel: '25%',
    basePoints: 1,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Black female board members',
    denominatorLabel: 'All board members',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.executive_directors.black_people',
    elementKey: 'management_control',
    displayName: 'Black executive directors',
    target: 0.5,
    targetLabel: '50%',
    basePoints: 2,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Black executive directors',
    denominatorLabel: 'All executive directors',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.executive_directors.black_women',
    elementKey: 'management_control',
    displayName: 'Black female executive directors',
    target: 0.25,
    targetLabel: '25%',
    basePoints: 1,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Black female executive directors',
    denominatorLabel: 'All executive directors',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.other_executive_management.black_people',
    elementKey: 'management_control',
    displayName: 'Black other executive management',
    target: 0.6,
    targetLabel: '60%',
    basePoints: 2,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Black other executive management',
    denominatorLabel: 'All other executive management',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.other_executive_management.black_women',
    elementKey: 'management_control',
    displayName: 'Black female other executive management',
    target: 0.3,
    targetLabel: '30%',
    basePoints: 1,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Black female other executive management',
    denominatorLabel: 'All other executive management',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.senior_management.black_people',
    elementKey: 'management_control',
    displayName: 'Black employees in senior management',
    target: 0.6,
    targetLabel: '60%',
    basePoints: 2,
    bonusPoints: 0,
    scoringMethod: 'eap_disaggregated',
    numeratorLabel: 'Black senior management',
    denominatorLabel: 'All senior management',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.senior_management.black_women',
    elementKey: 'management_control',
    displayName: 'Black female employees in senior management',
    target: 0.3,
    targetLabel: '30%',
    basePoints: 1,
    bonusPoints: 0,
    scoringMethod: 'eap_disaggregated',
    numeratorLabel: 'Black female senior management',
    denominatorLabel: 'All senior management',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.middle_management.black_people',
    elementKey: 'management_control',
    displayName: 'Black employees in middle management',
    target: 0.75,
    targetLabel: '75%',
    basePoints: 2,
    bonusPoints: 0,
    scoringMethod: 'eap_disaggregated',
    numeratorLabel: 'Black middle management',
    denominatorLabel: 'All middle management',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.middle_management.black_women',
    elementKey: 'management_control',
    displayName: 'Black female employees in middle management',
    target: 0.38,
    targetLabel: '38%',
    basePoints: 1,
    bonusPoints: 0,
    scoringMethod: 'eap_disaggregated',
    numeratorLabel: 'Black female middle management',
    denominatorLabel: 'All middle management',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.junior_management.black_people',
    elementKey: 'management_control',
    displayName: 'Black employees in junior management',
    target: 0.88,
    targetLabel: '88%',
    basePoints: 1,
    bonusPoints: 0,
    scoringMethod: 'eap_disaggregated',
    numeratorLabel: 'Black junior management',
    denominatorLabel: 'All junior management',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.junior_management.black_women',
    elementKey: 'management_control',
    displayName: 'Black female employees in junior management',
    target: 0.44,
    targetLabel: '44%',
    basePoints: 1,
    bonusPoints: 0,
    scoringMethod: 'eap_disaggregated',
    numeratorLabel: 'Black female junior management',
    denominatorLabel: 'All junior management',
    source: STATEMENT_200,
  },
  {
    key: 'management_control.employees_with_disabilities.black_people',
    elementKey: 'management_control',
    displayName: 'Black employees with disabilities',
    target: 0.02,
    targetLabel: '2%',
    basePoints: 2,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Black employees with disabilities',
    denominatorLabel: 'All employees',
    source: STATEMENT_200,
  },
]

const SKILLS_DEVELOPMENT_INDICATORS: IndicatorRule[] = [
  {
    key: 'skills_development.expenditure.black_people',
    elementKey: 'skills_development',
    displayName: 'Skills development expenditure on learning programmes for black people',
    target: 0.035,
    targetLabel: '3.5% of leviable amount',
    basePoints: 6,
    bonusPoints: 0,
    scoringMethod: 'eap_disaggregated',
    numeratorLabel: 'Recognised skills development expenditure on black people',
    denominatorLabel: 'Leviable amount',
    source: STATEMENT_300,
  },
  {
    key: 'skills_development.bursaries.black_students',
    elementKey: 'skills_development',
    displayName: 'Skills development expenditure on bursaries for black students at higher education institutions',
    target: 0.025,
    targetLabel: '2.5% of leviable amount',
    basePoints: 4,
    bonusPoints: 0,
    scoringMethod: 'eap_disaggregated',
    numeratorLabel: 'Recognised bursary expenditure for black students',
    denominatorLabel: 'Leviable amount',
    source: STATEMENT_300,
  },
  {
    key: 'skills_development.expenditure.disabled_black_people',
    elementKey: 'skills_development',
    displayName: 'Skills development expenditure on learning programmes for black employees with disabilities',
    target: 0.003,
    targetLabel: '0.3% of leviable amount',
    basePoints: 4,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Recognised expenditure on black employees with disabilities',
    denominatorLabel: 'Leviable amount',
    source: STATEMENT_300,
  },
  {
    key: 'skills_development.learnerships',
    elementKey: 'skills_development',
    displayName: 'Black people in learnerships, apprenticeships and internships',
    target: 0.05,
    targetLabel: '5% of total employees',
    basePoints: 6,
    bonusPoints: 0,
    scoringMethod: 'eap_disaggregated',
    numeratorLabel: 'Black people participating in learnerships, apprenticeships and internships',
    denominatorLabel: 'Total employees',
    source: STATEMENT_300,
  },
  {
    key: 'skills_development.bonus.absorption',
    elementKey: 'skills_development',
    displayName: 'Bonus: absorption of black learners at the end of a learnership, apprenticeship or internship',
    target: 1,
    targetLabel: '100% of learners who completed',
    basePoints: 0,
    bonusPoints: 5,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Black learners absorbed into permanent employment',
    denominatorLabel: 'Black learners who completed a learning programme',
    source: STATEMENT_300,
    notes:
      'The reference workbook divides completed learners by total headcount, which is not the absorption measure. This rule set uses absorbed / completed.',
  },
]

const PROCUREMENT_INDICATORS: IndicatorRule[] = [
  {
    key: 'preferential_procurement.all_empowering_suppliers',
    elementKey: 'preferential_procurement',
    displayName: 'B-BBEE procurement spend from all empowering suppliers',
    target: 0.8,
    targetLabel: '80% of TMPS',
    basePoints: 5,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'B-BBEE procurement spend from all empowering suppliers',
    denominatorLabel: 'Total measured procurement spend',
    source: STATEMENT_400,
  },
  {
    key: 'preferential_procurement.qse',
    elementKey: 'preferential_procurement',
    displayName: 'B-BBEE procurement spend from empowering suppliers that are QSEs',
    target: 0.15,
    targetLabel: '15% of TMPS',
    basePoints: 3,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'B-BBEE procurement spend from QSE suppliers',
    denominatorLabel: 'Total measured procurement spend',
    source: STATEMENT_400,
  },
  {
    key: 'preferential_procurement.eme',
    elementKey: 'preferential_procurement',
    displayName: 'B-BBEE procurement spend from empowering suppliers that are EMEs',
    target: 0.15,
    targetLabel: '15% of TMPS',
    basePoints: 4,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'B-BBEE procurement spend from EME suppliers',
    denominatorLabel: 'Total measured procurement spend',
    source: STATEMENT_400,
  },
  {
    key: 'preferential_procurement.black_owned_51',
    elementKey: 'preferential_procurement',
    displayName: 'B-BBEE procurement spend from empowering suppliers that are at least 51% black owned',
    target: 0.5,
    targetLabel: '50% of TMPS',
    basePoints: 11,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'B-BBEE procurement spend from at least 51% black-owned suppliers',
    denominatorLabel: 'Total measured procurement spend',
    source: STATEMENT_400,
    notes: 'Increased from 9 points at 40% to 11 points at 50% by GN 304 of 2019.',
  },
  {
    key: 'preferential_procurement.black_women_owned_30',
    elementKey: 'preferential_procurement',
    displayName: 'B-BBEE procurement spend from empowering suppliers that are at least 30% black women owned',
    target: 0.12,
    targetLabel: '12% of TMPS',
    basePoints: 4,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'B-BBEE procurement spend from at least 30% black-women-owned suppliers',
    denominatorLabel: 'Total measured procurement spend',
    source: STATEMENT_400,
  },
  {
    key: 'preferential_procurement.bonus.designated_group',
    elementKey: 'preferential_procurement',
    displayName: 'Bonus: procurement spend from empowering designated group suppliers that are at least 51% black owned',
    target: 0.02,
    targetLabel: '2% of TMPS',
    basePoints: 0,
    bonusPoints: 2,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Procurement spend from designated group suppliers',
    denominatorLabel: 'Total measured procurement spend',
    source: STATEMENT_400,
  },
]

const SUPPLIER_DEVELOPMENT_INDICATORS: IndicatorRule[] = [
  {
    key: 'supplier_development.contributions',
    elementKey: 'supplier_development',
    displayName: 'Annual value of all supplier development contributions',
    target: 0.02,
    targetLabel: '2% of applicable NPAT',
    basePoints: 10,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Recognised supplier development contributions',
    denominatorLabel: 'Applicable NPAT',
    source: STATEMENT_400,
  },
  {
    key: 'supplier_development.bonus.graduation',
    elementKey: 'supplier_development',
    displayName: 'Bonus: graduation of one or more enterprise development beneficiaries to supplier development level',
    target: 1,
    targetLabel: 'Confirmed graduation',
    basePoints: 0,
    bonusPoints: 1,
    scoringMethod: 'boolean_bonus',
    numeratorLabel: 'Confirmed graduation with evidence',
    denominatorLabel: 'n/a',
    source: STATEMENT_400,
  },
]

const ENTERPRISE_DEVELOPMENT_INDICATORS: IndicatorRule[] = [
  {
    key: 'enterprise_development.contributions',
    elementKey: 'enterprise_development',
    displayName: 'Annual value of enterprise development contributions and sector specific programmes',
    target: 0.01,
    targetLabel: '1% of applicable NPAT',
    basePoints: 5,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Recognised enterprise development contributions',
    denominatorLabel: 'Applicable NPAT',
    source: STATEMENT_400,
  },
  {
    key: 'enterprise_development.bonus.job_creation',
    elementKey: 'enterprise_development',
    displayName: 'Bonus: job creation arising from enterprise and supplier development initiatives',
    target: 1,
    targetLabel: 'Confirmed job creation',
    basePoints: 0,
    bonusPoints: 1,
    scoringMethod: 'boolean_bonus',
    numeratorLabel: 'Confirmed job creation with evidence',
    denominatorLabel: 'n/a',
    source: STATEMENT_400,
  },
]

const SED_INDICATORS: IndicatorRule[] = [
  {
    key: 'socio_economic_development.contributions',
    elementKey: 'socio_economic_development',
    displayName: 'Annual value of all socio-economic development contributions',
    target: 0.01,
    targetLabel: '1% of applicable NPAT',
    basePoints: 5,
    bonusPoints: 0,
    scoringMethod: 'proportional_capped',
    numeratorLabel: 'Recognised socio-economic development contributions',
    denominatorLabel: 'Applicable NPAT',
    source: STATEMENT_500,
  },
]

const RULE_CONFLICTS: RuleConflict[] = [
  {
    key: 'procurement-available-points',
    topic: 'Preferential procurement available base points',
    workbookOrCommonPosition:
      'Preferential procurement is commonly quoted as 25 base points, carried over from the pre-2019 scorecard where 51% black-owned procurement carried 9 points at a 40% target.',
    gazettedPosition:
      'Statement 400 §2.1 weights the five base procurement indicators to 5 + 3 + 4 + 11 + 4 = 27 points, because GN 304 of 2019 raised 51% black-owned procurement to 11 points at a 50% target.',
    resolution:
      'Available base points are 27. The reference workbook agrees (Procurement Scorecard!C12 = 27).',
    source: STATEMENT_400,
  },
  {
    key: 'procurement-subminimum-basis',
    topic: 'Preferential procurement priority sub-minimum basis',
    workbookOrCommonPosition:
      'A 40% sub-minimum applied to the 27 available points would require 10.8 points.',
    gazettedPosition:
      'Statement 000 §3.3.1.3.1 fixes the preferential procurement sub-minimum at "40% of the 25 points" and was not updated when Statement 400 moved the weighting to 27.',
    resolution:
      'The sub-minimum threshold is 40% of 25 = 10.0 points, measured against actual base points achieved out of 27. Both figures are gazetted; the engine applies each in the place the gazette puts it.',
    source: STATEMENT_000,
  },
  {
    key: 'generic-total-points',
    topic: 'Total generic scorecard points',
    workbookOrCommonPosition:
      'Statement 000 §9.1 summarises the generic scorecard as 109 (118) points with Enterprise and Supplier Development at 40 points.',
    gazettedPosition:
      'The Statement 400 indicator weightings sum to 42 base points for Enterprise and Supplier Development (27 + 10 + 5), giving 111 base points overall.',
    resolution:
      'The engine totals the operative indicator weightings: 111 base points and 9 bonus points. The 109/118 summary figure is treated as a stale cross-reference in Statement 000.',
    source: STATEMENT_400,
  },
  {
    key: 'npat-denominator-selection',
    topic: 'Applicable NPAT denominator',
    workbookOrCommonPosition:
      'The reference workbook labels NPAT Calculation!B25 "Apply the greater of the two for calculation purposes" but B27 is hard-wired to =B23 (actual NPAT), so deemed NPAT never applies.',
    gazettedPosition:
      'Where NPAT is a negative or is lower than a quarter of the industry norm, the deemed NPAT (indicative profit margin applied to revenue) is used instead.',
    resolution:
      'The engine resolves the denominator explicitly, shows which value was selected and why, and requires an authorised override with a reason where the rule cannot be resolved from the supplied inputs.',
    source: STATEMENT_400,
  },
  {
    key: 'absorption-measure',
    topic: 'Skills development absorption bonus measure',
    workbookOrCommonPosition:
      'The reference workbook computes absorption as completed learners divided by total headcount (Skills Development!B115 / B116).',
    gazettedPosition:
      'Statement 300 measures absorption of black learners who completed a learnership, apprenticeship or internship into permanent employment.',
    resolution: 'The engine uses absorbed learners divided by learners who completed.',
    source: STATEMENT_300,
  },
  {
    key: 'plus-one-vote',
    topic: 'Ownership voting rights "25% plus one vote"',
    workbookOrCommonPosition:
      'The reference workbook hard-codes the target as 25.1% (Ownership!E4 and Full Scorecard!E5).',
    gazettedPosition: 'Statement 100 sets the target at 25% plus one vote.',
    resolution:
      'Where total and black exercisable vote counts are supplied the engine computes the exact target as (25% of total votes + 1) / total votes. The 25.1% approximation is only used as a labelled fallback.',
    source: STATEMENT_100,
  },
  {
    key: 'skills-total-mixes-bonus',
    topic: 'Skills development total',
    workbookOrCommonPosition:
      'Skills Development!E17 sums the 5 absorption bonus points into a total whose available points (C17) is 20 base points only.',
    gazettedPosition: 'Statement 300 separates 20 base points from 5 bonus points.',
    resolution: 'The engine reports base and bonus points separately for every element.',
    source: STATEMENT_300,
  },
  {
    key: 'esd-orphan-job-creation-row',
    topic: '"11% more new jobs created as a result of ESD initiatives" — 2 points',
    workbookOrCommonPosition:
      'The reference workbook carries this row at ED & SD!A15 with 2 points, but excludes it from its own total (ED & SD!E17 sums E5, E8, E11 and E13 only).',
    gazettedPosition: 'Statement 400 provides 1 bonus point for job creation, not 2.',
    resolution:
      'The orphan row is excluded. Job creation is implemented as a single 1-point bonus pending REAP confirmation of the workbook row.',
    source: STATEMENT_400,
  },
]

export const GENERIC_CODES_2019_V1: RuleSet = {
  key: 'generic-codes-2019-v1',
  version: '1.0.0',
  displayName: 'Amended Codes of Good Practice — Generic scorecard (2019 amendments)',
  status: 'active',
  effectiveFrom: '2019-12-01',
  selectableAsOperative: true,
  primarySources: [STATEMENT_000, STATEMENT_100, STATEMENT_200, STATEMENT_300, STATEMENT_400, STATEMENT_500],
  elements: [
    { elementKey: 'ownership', displayName: 'Ownership', basePoints: 25, bonusPoints: 0 },
    { elementKey: 'management_control', displayName: 'Management Control', basePoints: 19, bonusPoints: 0 },
    { elementKey: 'skills_development', displayName: 'Skills Development', basePoints: 20, bonusPoints: 5 },
    { elementKey: 'preferential_procurement', displayName: 'Preferential Procurement', basePoints: 27, bonusPoints: 2 },
    { elementKey: 'supplier_development', displayName: 'Supplier Development', basePoints: 10, bonusPoints: 1 },
    { elementKey: 'enterprise_development', displayName: 'Enterprise Development', basePoints: 5, bonusPoints: 1 },
    { elementKey: 'socio_economic_development', displayName: 'Socio-Economic Development', basePoints: 5, bonusPoints: 0 },
  ],
  indicators: [
    ...OWNERSHIP_INDICATORS,
    ...MANAGEMENT_CONTROL_INDICATORS,
    ...SKILLS_DEVELOPMENT_INDICATORS,
    ...PROCUREMENT_INDICATORS,
    ...SUPPLIER_DEVELOPMENT_INDICATORS,
    ...ENTERPRISE_DEVELOPMENT_INDICATORS,
    ...SED_INDICATORS,
  ],
  prioritySubminimums: [
    {
      key: 'priority.ownership.net_value',
      label: 'Ownership — net value',
      elementKey: 'ownership',
      basisPoints: 8,
      fraction: 0.4,
      measure: 'ownership_net_value_points',
      source: STATEMENT_000,
    },
    {
      key: 'priority.skills_development',
      label: 'Skills Development',
      elementKey: 'skills_development',
      basisPoints: 20,
      fraction: 0.4,
      measure: 'element_base_points',
      source: STATEMENT_000,
    },
    {
      key: 'priority.preferential_procurement',
      label: 'Enterprise and Supplier Development — preferential procurement',
      elementKey: 'preferential_procurement',
      basisPoints: 25,
      fraction: 0.4,
      measure: 'element_base_points',
      source: STATEMENT_000,
    },
    {
      key: 'priority.supplier_development',
      label: 'Enterprise and Supplier Development — supplier development',
      elementKey: 'supplier_development',
      basisPoints: 10,
      fraction: 0.4,
      measure: 'element_base_points',
      source: STATEMENT_000,
    },
    {
      key: 'priority.enterprise_development',
      label: 'Enterprise and Supplier Development — enterprise development',
      elementKey: 'enterprise_development',
      basisPoints: 5,
      fraction: 0.4,
      measure: 'element_base_points',
      source: STATEMENT_000,
    },
  ],
  levelBands: GENERIC_2019_LEVEL_BANDS,
  ruleConflicts: RULE_CONFLICTS,
}
