/**
 * Machine-readable inventory of every scoring rule expressed in the reference
 * workbook `Generic-Scorecard Calculator.xlsx`
 * (SHA-256 93494e2916e21ad88072a074edadc75d351db6f28c10222463df8de641168fc0).
 *
 * This file records what the workbook does. It is NOT the calculation engine:
 * runtime scoring uses the gazetted rule set in `./scorecard.ts`. The inventory
 * exists so the parity report, regression tests and the in-app rule provenance
 * panel all read from one source.
 *
 * No workbook cell values, personal records or supplier records are reproduced
 * here — only cell addresses, formulas and rule metadata.
 */

export type MissingInputBehaviour =
  /** Engine returns null points and marks the element as needing review. */
  | 'no_score_needs_review'
  /** Engine scores zero because an absent contribution genuinely earns zero. */
  | 'score_zero'
  /** Engine blocks the indicator until an authorised user confirms the rule. */
  | 'blocked_pending_confirmation'

export type OfficialRuleStatus =
  | 'matches_official_source'
  | 'replaced_with_official_rule'
  | 'requires_reap_confirmation'
  | 'not_a_scoring_rule'

export type WorkbookParityStatus =
  | 'exact_parity'
  | 'corrected_workbook_defect'
  | 'replaced_with_official_rule'
  | 'requires_reap_confirmation'
  | 'excluded_demonstration_data'
  | 'unsupported_or_orphaned'

export type WorkbookRuleRecord = {
  /** Engine indicator key, or null where the workbook row has no engine rule. */
  indicatorKey: string | null
  displayName: string
  workbookSheet: string
  /** Addresses of the cells that express this rule in the workbook. */
  workbookCells: {
    target?: string
    availablePoints?: string
    achievedPercentage?: string
    pointsAchieved?: string
    numerator?: string
    denominator?: string
  }
  /** Target as a fraction, or null where the workbook has no numeric target. */
  target: number | null
  targetLabel: string
  basePoints: number
  bonusPoints: number
  numerator: string
  denominator: string
  /** Cap applied by the workbook or by the rule, expressed in words. */
  cap: string | null
  /** The workbook formula, verbatim. */
  workbookFormula: string | null
  sourceDataSheets: string[]
  missingInputBehaviour: MissingInputBehaviour
  officialRuleStatus: OfficialRuleStatus
  workbookParityStatus: WorkbookParityStatus
  knownWorkbookDefect: string | null
}

const CAP_PROPORTIONAL = 'min(actual / target, 1) × available points'

export const WORKBOOK_RULE_INVENTORY: WorkbookRuleRecord[] = [
  // ---------------------------------------------------------------- Ownership
  {
    indicatorKey: 'ownership.voting_rights.black_people',
    displayName: 'Voting rights — black people',
    workbookSheet: 'Ownership',
    workbookCells: { target: 'C4', availablePoints: 'B4', achievedPercentage: 'D4', pointsAchieved: 'E4' },
    target: 0.25,
    targetLabel: '25% + 1 vote (workbook approximates as 25.1%)',
    basePoints: 4,
    bonusPoints: 0,
    numerator: 'Effective black shareholding (Ownership!H22)',
    denominator: 'Total shareholding',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'IF(C4=0,0,MIN(D4/25.1%*B4,B4))',
    sourceDataSheets: ['Ownership'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'replaced_with_official_rule',
    workbookParityStatus: 'replaced_with_official_rule',
    knownWorkbookDefect:
      'Hard-codes 25.1% instead of "25% plus one vote", and reads the same effective shareholding total (H22) used for economic interest, so voting rights are never captured separately.',
  },
  {
    indicatorKey: 'ownership.voting_rights.black_women',
    displayName: 'Voting rights — black women',
    workbookSheet: 'Ownership',
    workbookCells: { target: 'C5', availablePoints: 'B5', achievedPercentage: 'D5', pointsAchieved: 'E5' },
    target: 0.1,
    targetLabel: '10%',
    basePoints: 2,
    bonusPoints: 0,
    numerator: 'Effective black women shareholding (Ownership!I22)',
    denominator: 'Total shareholding',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'IF(C5=0,0,MIN(D5/C5*B5,B5))',
    sourceDataSheets: ['Ownership'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: 'Reads the economic-interest total rather than a separate voting-rights capture.',
  },
  {
    indicatorKey: 'ownership.economic_interest.black_people',
    displayName: 'Economic interest — black people',
    workbookSheet: 'Ownership',
    workbookCells: { target: 'C6', availablePoints: 'B6', achievedPercentage: 'D6', pointsAchieved: 'E6' },
    target: 0.25,
    targetLabel: '25%',
    basePoints: 4,
    bonusPoints: 0,
    numerator: 'Ownership!H22',
    denominator: 'Total economic interest',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'IF(C6=0,0,MIN(D6/C6*B6,B6))',
    sourceDataSheets: ['Ownership'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: null,
  },
  {
    indicatorKey: 'ownership.economic_interest.black_women',
    displayName: 'Economic interest — black women',
    workbookSheet: 'Ownership',
    workbookCells: { target: 'C7', availablePoints: 'B7', achievedPercentage: 'D7', pointsAchieved: 'E7' },
    target: 0.1,
    targetLabel: '10%',
    basePoints: 2,
    bonusPoints: 0,
    numerator: 'Ownership!I22',
    denominator: 'Total economic interest',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'IF(C7=0,0,MIN(D7/C7*B7,B7))',
    sourceDataSheets: ['Ownership'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: null,
  },
  {
    indicatorKey: 'ownership.economic_interest.designated_groups',
    displayName: 'Economic interest — ESOP, black designated groups, B-BBEE schemes',
    workbookSheet: 'Ownership',
    workbookCells: { target: 'C8', availablePoints: 'B8', achievedPercentage: 'D8', pointsAchieved: 'E8' },
    target: 0.03,
    targetLabel: '3%',
    basePoints: 3,
    bonusPoints: 0,
    numerator: 'Ownership!J22',
    denominator: 'Total economic interest',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'IF(C8=0,0,MIN(D8/C8*B8,B8))',
    sourceDataSheets: ['Ownership'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: null,
  },
  {
    indicatorKey: 'ownership.new_entrants',
    displayName: 'Economic interest — black new entrants',
    workbookSheet: 'Ownership',
    workbookCells: { target: 'C10', availablePoints: 'B10', achievedPercentage: 'D10', pointsAchieved: 'E10' },
    target: 0.02,
    targetLabel: '2%',
    basePoints: 2,
    bonusPoints: 0,
    numerator: 'Ownership!K22',
    denominator: 'Total economic interest',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'IF(C10=0,0,MIN(D10/C10*B10,B10))',
    sourceDataSheets: ['Ownership'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: null,
  },
  {
    indicatorKey: 'ownership.net_value',
    displayName: 'Net value',
    workbookSheet: 'Ownership',
    workbookCells: { target: 'C11', availablePoints: 'B11', achievedPercentage: 'D11', pointsAchieved: 'E11' },
    target: 0.25,
    targetLabel: '25%',
    basePoints: 8,
    bonusPoints: 0,
    numerator: 'Ownership!H22 (black shareholding reused as net value)',
    denominator: 'Target net value',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'IF(C11=0,0,MIN(D11/C11*B11,B11))',
    sourceDataSheets: ['Ownership'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'replaced_with_official_rule',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'Net value is set equal to the black shareholding percentage. There is no deemed-net-value, acquisition-debt or Annexe 100(E) time-based graduation calculation, so a fully geared transaction scores full net-value points.',
  },
  {
    indicatorKey: null,
    displayName: 'Ownership shareholder demonstration rows',
    workbookSheet: 'Ownership',
    workbookCells: { numerator: 'C17:G21', denominator: 'H22:K22' },
    target: null,
    targetLabel: 'n/a',
    basePoints: 0,
    bonusPoints: 0,
    numerator: 'Five shareholder rows, one of which carries a 25% / 100% black demonstration entry',
    denominator: 'n/a',
    cap: null,
    workbookFormula: '$C$17*D17 … SUM(H17:H21)',
    sourceDataSheets: ['Ownership'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'not_a_scoring_rule',
    workbookParityStatus: 'excluded_demonstration_data',
    knownWorkbookDefect: 'Demonstration shareholding is present in the shipped workbook and must never be imported as client data.',
  },

  // ------------------------------------------------------- Management Control
  {
    indicatorKey: 'management_control.board.black_people',
    displayName: 'Board — black people',
    workbookSheet: 'Management Control',
    workbookCells: {
      target: 'B5',
      availablePoints: 'C5',
      achievedPercentage: 'D5',
      pointsAchieved: 'E5',
      numerator: 'G4',
      denominator: 'G5',
    },
    target: 0.5,
    targetLabel: '50%',
    basePoints: 2,
    bonusPoints: 0,
    numerator: 'Black board members',
    denominator: 'Total board members',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D5/B5*C5,C5) where D5 = G4/G5',
    sourceDataSheets: ['3 Board Members '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'Denominator cells are blank in the shipped workbook, so D5 caches #DIV/0! and E5 inherits the error. The engine returns no score and requests the missing denominator instead.',
  },
  {
    indicatorKey: 'management_control.board.black_women',
    displayName: 'Board — black women',
    workbookSheet: 'Management Control',
    workbookCells: {
      target: 'B7',
      availablePoints: 'C7',
      achievedPercentage: 'D7',
      pointsAchieved: 'E7',
      numerator: 'G7',
      denominator: 'G8',
    },
    target: 0.25,
    targetLabel: '25%',
    basePoints: 1,
    bonusPoints: 0,
    numerator: 'Black female board members',
    denominator: 'Total board members',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D7/B7*C7,C7) where D7 = G7/G8',
    sourceDataSheets: ['3 Board Members '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Cached #DIV/0! on an empty register.',
  },
  {
    indicatorKey: 'management_control.executive_directors.black_people',
    displayName: 'Executive directors — black people',
    workbookSheet: 'Management Control',
    workbookCells: {
      target: 'B9',
      availablePoints: 'C9',
      achievedPercentage: 'D9',
      pointsAchieved: 'E9',
      numerator: 'G10',
      denominator: 'G11',
    },
    target: 0.5,
    targetLabel: '50%',
    basePoints: 2,
    bonusPoints: 0,
    numerator: 'Black executive directors',
    denominator: 'Total executive directors',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D9/B9*C9,C9) where D9 = G10/G11',
    sourceDataSheets: ['4 Executive Committe '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Cached #DIV/0! on an empty register.',
  },
  {
    indicatorKey: 'management_control.executive_directors.black_women',
    displayName: 'Executive directors — black women',
    workbookSheet: 'Management Control',
    workbookCells: {
      target: 'B11',
      availablePoints: 'C11',
      achievedPercentage: 'D11',
      pointsAchieved: 'E11',
      numerator: 'G13',
      denominator: 'G14',
    },
    target: 0.25,
    targetLabel: '25%',
    basePoints: 1,
    bonusPoints: 0,
    numerator: 'Black female executive directors',
    denominator: 'Total executive directors',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D11/B11*C11,C11) where D11 = G13/G14',
    sourceDataSheets: ['4 Executive Committe '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Cached #DIV/0! on an empty register.',
  },
  {
    indicatorKey: 'management_control.other_executive_management.black_people',
    displayName: 'Other executive management — black people',
    workbookSheet: 'Management Control',
    workbookCells: {
      target: 'B14',
      availablePoints: 'C14',
      achievedPercentage: 'D14',
      pointsAchieved: 'E14',
      numerator: 'G16',
      denominator: 'G17',
    },
    target: 0.6,
    targetLabel: '60%',
    basePoints: 2,
    bonusPoints: 0,
    numerator: 'Black executive management',
    denominator: 'Total executive management',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D14/B14*C14,C14) where D14 = G16/G17',
    sourceDataSheets: ['4 Executive Committe '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'Row label reads "as a % of all executive directors" while the formula divides by total executive management. Cached #DIV/0!.',
  },
  {
    indicatorKey: 'management_control.other_executive_management.black_women',
    displayName: 'Other executive management — black women',
    workbookSheet: 'Management Control',
    workbookCells: {
      target: 'B16',
      availablePoints: 'C16',
      achievedPercentage: 'D16',
      pointsAchieved: 'E16',
      numerator: 'G19',
      denominator: 'G20',
    },
    target: 0.3,
    targetLabel: '30%',
    basePoints: 1,
    bonusPoints: 0,
    numerator: 'Black female executive management',
    denominator: 'Total executive management',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D16/B16*C16,C16) where D16 = G19/G20',
    sourceDataSheets: ['4 Executive Committe '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'The numerator input cell G19 is labelled "Black Executive Management", identical to G16, rather than "Black Female Executive Management". A user filling in the workbook as labelled would score the female indicator off the total black figure.',
  },
  {
    indicatorKey: 'management_control.senior_management.black_people',
    displayName: 'Senior management — black people',
    workbookSheet: 'Employment Equity',
    workbookCells: {
      target: 'B5',
      availablePoints: 'C5',
      achievedPercentage: 'D5',
      pointsAchieved: 'E5',
      numerator: 'B29:G29',
      denominator: 'H29',
    },
    target: 0.6,
    targetLabel: '60%, EAP-disaggregated across six race/gender bands',
    basePoints: 2,
    bonusPoints: 0,
    numerator: 'Senior management headcount by race and gender',
    denominator: 'Total senior management',
    cap: 'Per-band maximum allowable points, summed',
    workbookFormula: 'SUM over bands of MIN((share/splitTarget)*maxBandPoints, maxBandPoints)',
    sourceDataSheets: ['5 Staff List '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'EAP percentages are hard-coded at B30:G30 (43.5 / 4.6 / 1.7 / 37.5 / 4.2 / 1.0). D5 back-computes the achieved percentage from the points awarded rather than measuring it. H50 sums B49:G51, one row wider than the data.',
  },
  {
    indicatorKey: 'management_control.senior_management.black_women',
    displayName: 'Senior management — black women',
    workbookSheet: 'Employment Equity',
    workbookCells: { target: 'B7', availablePoints: 'C7', achievedPercentage: 'D7', pointsAchieved: 'E7' },
    target: 0.3,
    targetLabel: '30%, EAP-disaggregated across three female bands',
    basePoints: 1,
    bonusPoints: 0,
    numerator: 'Female senior management headcount by race',
    denominator: 'Total senior management',
    cap: 'Per-band maximum allowable points, summed',
    workbookFormula: 'SUM over female bands of MIN((share/splitTarget)*maxBandPoints, maxBandPoints)',
    sourceDataSheets: ['5 Staff List '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Hard-coded EAP; H79 sums E78:G80, one row wider than the data.',
  },
  {
    indicatorKey: 'management_control.middle_management.black_people',
    displayName: 'Middle management — black people',
    workbookSheet: 'Employment Equity',
    workbookCells: { target: 'B10', availablePoints: 'C10', achievedPercentage: 'D10', pointsAchieved: 'E10' },
    target: 0.75,
    targetLabel: '75%, EAP-disaggregated',
    basePoints: 2,
    bonusPoints: 0,
    numerator: 'Middle management headcount by race and gender',
    denominator: 'Total middle management',
    cap: 'Per-band maximum allowable points, summed',
    workbookFormula: 'SUM over bands of MIN((share/splitTarget)*maxBandPoints, maxBandPoints)',
    sourceDataSheets: ['5 Staff List '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Hard-coded EAP; H108 sums one row wider than the data.',
  },
  {
    indicatorKey: 'management_control.middle_management.black_women',
    displayName: 'Middle management — black women',
    workbookSheet: 'Employment Equity',
    workbookCells: { target: 'B12', availablePoints: 'C12', achievedPercentage: 'D12', pointsAchieved: 'E12' },
    target: 0.38,
    targetLabel: '38%, EAP-disaggregated',
    basePoints: 1,
    bonusPoints: 0,
    numerator: 'Female middle management headcount by race',
    denominator: 'Total middle management',
    cap: 'Per-band maximum allowable points, summed',
    workbookFormula: 'SUM over female bands of MIN((share/splitTarget)*maxBandPoints, maxBandPoints)',
    sourceDataSheets: ['5 Staff List '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Hard-coded EAP; H139 sums one row wider than the data.',
  },
  {
    indicatorKey: 'management_control.junior_management.black_people',
    displayName: 'Junior management — black people',
    workbookSheet: 'Employment Equity',
    workbookCells: { target: 'B15', availablePoints: 'C15', achievedPercentage: 'D15', pointsAchieved: 'E15' },
    target: 0.88,
    targetLabel: '88%, EAP-disaggregated',
    basePoints: 1,
    bonusPoints: 0,
    numerator: 'Junior management headcount by race and gender',
    denominator: 'Total junior management',
    cap: 'Per-band maximum allowable points, summed',
    workbookFormula: 'SUM over bands of MIN((share/splitTarget)*maxBandPoints, maxBandPoints)',
    sourceDataSheets: ['5 Staff List '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Hard-coded EAP; H168 sums one row wider than the data.',
  },
  {
    indicatorKey: 'management_control.junior_management.black_women',
    displayName: 'Junior management — black women',
    workbookSheet: 'Employment Equity',
    workbookCells: { target: 'B17', availablePoints: 'C17', achievedPercentage: 'D17', pointsAchieved: 'E17' },
    target: 0.44,
    targetLabel: '44%, EAP-disaggregated',
    basePoints: 1,
    bonusPoints: 0,
    numerator: 'Female junior management headcount by race',
    denominator: 'Total junior management',
    cap: 'Per-band maximum allowable points, summed',
    workbookFormula: 'SUM over female bands of MIN((share/splitTarget)*maxBandPoints, maxBandPoints)',
    sourceDataSheets: ['5 Staff List '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Hard-coded EAP; H197 sums one row wider than the data.',
  },
  {
    indicatorKey: 'management_control.employees_with_disabilities.black_people',
    displayName: 'Black employees with disabilities',
    workbookSheet: 'Employment Equity',
    workbookCells: {
      target: 'B20',
      availablePoints: 'C20',
      achievedPercentage: 'D20',
      pointsAchieved: 'E20',
      numerator: 'B204',
      denominator: 'B205',
    },
    target: 0.02,
    targetLabel: '2%',
    basePoints: 2,
    bonusPoints: 0,
    numerator: 'Black employees with disabilities',
    denominator: 'Total employees',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D20/B20*C20,C20) where D20 = B204/B205',
    sourceDataSheets: ['5 Staff List '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Manual entry cells, not derived from the staff list. Cached #DIV/0! when blank.',
  },
  {
    indicatorKey: null,
    displayName: 'Management Control element total',
    workbookSheet: 'Employment Equity',
    workbookCells: { availablePoints: 'C22', pointsAchieved: 'E22' },
    target: null,
    targetLabel: 'n/a',
    basePoints: 19,
    bonusPoints: 0,
    numerator: 'Management Control!C18 (9 points) + Employment Equity rows (10 points)',
    denominator: 'n/a',
    cap: null,
    workbookFormula:
      "'Management Control'!C18+'Employment Equity'!C5:C6+'Employment Equity'!C7:C8+'Employment Equity'!C10:C11+'Employment Equity'!C12:C13+'Employment Equity'!C15:C16+'Employment Equity'!C17:C18+'Employment Equity'!C20:C21",
    sourceDataSheets: ['Management Control', 'Employment Equity'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'Relies on Excel implicit range intersection (C5:C6 style references inside a scalar sum). Correct only by accident of the current row layout and breaks if a row is inserted.',
  },

  // ------------------------------------------------------ Skills Development
  {
    indicatorKey: 'skills_development.expenditure.black_people',
    displayName: 'Skills development expenditure — black people',
    workbookSheet: 'Skills Development ',
    workbookCells: { target: 'B5', availablePoints: 'C5', achievedPercentage: 'D5', pointsAchieved: 'E5' },
    target: 0.035,
    targetLabel: '3.5% of leviable amount, EAP-disaggregated',
    basePoints: 6,
    bonusPoints: 0,
    numerator: 'Recognised training spend by race and gender',
    denominator: 'Leviable amount (Skills Development !H23)',
    cap: 'Per-band maximum allowable points, summed',
    workbookFormula: 'H44 = SUM(B43:G45), each MIN(share/splitTarget*maxBandPoints, maxBandPoints)',
    sourceDataSheets: ['Category A', 'Category BCDE', 'Category F&G', '13 EMP201'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'Leviable amount cell H23 is a manual entry that is never linked to the EMP201 sheet total, so the denominator is blank and the whole block caches #DIV/0!. EAP is hard-coded. D5 back-computes achieved percentage from points.',
  },
  {
    indicatorKey: 'skills_development.bursaries.black_students',
    displayName: 'Bursaries for black students',
    workbookSheet: 'Skills Development ',
    workbookCells: { target: 'B7', availablePoints: 'C7', achievedPercentage: 'D7', pointsAchieved: 'E7' },
    target: 0.025,
    targetLabel: '2.5% of leviable amount, EAP-disaggregated',
    basePoints: 4,
    bonusPoints: 0,
    numerator: 'Category A bursary spend by race and gender',
    denominator: 'Leviable amount (Skills Development !H52)',
    cap: 'Per-band maximum allowable points, summed',
    workbookFormula: 'H73 = SUM(B72:G74)',
    sourceDataSheets: ['Category A'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Separate unlinked leviable-amount cell (H52) from the one used at H23. Hard-coded EAP.',
  },
  {
    indicatorKey: 'skills_development.expenditure.disabled_black_people',
    displayName: 'Skills development expenditure — black employees with disabilities',
    workbookSheet: 'Skills Development ',
    workbookCells: {
      target: 'B9',
      availablePoints: 'C9',
      achievedPercentage: 'D9',
      pointsAchieved: 'E9',
      numerator: 'B109',
      denominator: 'B110',
    },
    target: 0.003,
    targetLabel: '0.3% of leviable amount',
    basePoints: 4,
    bonusPoints: 0,
    numerator: "Category A!U2 + Category BCDE!U2 + 'Category F&G'!U1",
    denominator: 'Leviable amount',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D9/B9*C9,C9) where D9 = B109/B110',
    sourceDataSheets: ['Category A', 'Category BCDE', 'Category F&G'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: 'Cached #DIV/0! because the leviable amount is blank.',
  },
  {
    indicatorKey: 'skills_development.learnerships',
    displayName: 'Black people in learnerships, apprenticeships and internships',
    workbookSheet: 'Skills Development ',
    workbookCells: { target: 'B12', availablePoints: 'C12', achievedPercentage: 'D12', pointsAchieved: 'E12' },
    target: 0.05,
    targetLabel: '5% of total employees, EAP-disaggregated',
    basePoints: 6,
    bonusPoints: 0,
    numerator: 'Category BCD(Hcount) headcount by race and gender',
    denominator: 'Total staff (Skills Development !H81)',
    cap: 'Per-band maximum allowable points, summed',
    workbookFormula: 'H102 = SUM(B101:G103)',
    sourceDataSheets: ['Category BCD(Hcount)'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Hard-coded EAP; total-staff denominator is a manual cell not linked to the staff list.',
  },
  {
    indicatorKey: 'skills_development.bonus.absorption',
    displayName: 'Bonus — absorption of learners',
    workbookSheet: 'Skills Development ',
    workbookCells: {
      target: 'B15',
      availablePoints: 'C15',
      achievedPercentage: 'D15',
      pointsAchieved: 'E15',
      numerator: 'B115',
      denominator: 'B116',
    },
    target: 1,
    targetLabel: '100%',
    basePoints: 0,
    bonusPoints: 5,
    numerator: 'Completed learners (workbook) / absorbed learners (official)',
    denominator: 'Total headcount (workbook) / learners who completed (official)',
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D15/B15*C15,C15) where D15 = B115/B116',
    sourceDataSheets: ['Category BCD(Hcount)', 'Learner summary '],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'replaced_with_official_rule',
    workbookParityStatus: 'replaced_with_official_rule',
    knownWorkbookDefect:
      'Measures completed learners against total headcount, which is not absorption. Replaced with absorbed / completed.',
  },
  {
    indicatorKey: null,
    displayName: 'Skills Development element total',
    workbookSheet: 'Skills Development ',
    workbookCells: { availablePoints: 'C17', pointsAchieved: 'E17' },
    target: null,
    targetLabel: 'n/a',
    basePoints: 20,
    bonusPoints: 5,
    numerator: 'Sum of skills indicators',
    denominator: 'n/a',
    cap: null,
    workbookFormula: 'C17 = SUM(C5,C7,C9,C12) = 20; E17 = SUM(E5:E10,E12:E13,E15)',
    sourceDataSheets: ['Skills Development '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'The achieved total includes the 5 absorption bonus points (E15) while the available total excludes them, so the element can report more than 100% of its own scale.',
  },

  // -------------------------------------------------- Preferential Procurement
  {
    indicatorKey: 'preferential_procurement.all_empowering_suppliers',
    displayName: 'Procurement — all B-BBEE suppliers',
    workbookSheet: 'Procurement Scorecard',
    workbookCells: { target: 'B5', availablePoints: 'C5', achievedPercentage: 'D5', pointsAchieved: 'E5' },
    target: 0.8,
    targetLabel: '80% of TMPS',
    basePoints: 5,
    bonusPoints: 0,
    numerator: "'7 TMPS '!F15",
    denominator: "'7 TMPS '!B25",
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D5/B5*C5,C5)',
    sourceDataSheets: ['Procurement Scorecard', '7 TMPS '],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'This row divides by B25 while every other procurement row divides by G10. B25 and G10 hold the same value today, so the inconsistency is latent rather than active.',
  },
  {
    indicatorKey: 'preferential_procurement.qse',
    displayName: 'Procurement — QSE suppliers',
    workbookSheet: 'Procurement Scorecard',
    workbookCells: { target: 'B6', availablePoints: 'C6', achievedPercentage: 'D6', pointsAchieved: 'E6' },
    target: 0.15,
    targetLabel: '15% of TMPS',
    basePoints: 3,
    bonusPoints: 0,
    numerator: "'7 TMPS '!G15",
    denominator: "'7 TMPS '!G10",
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D6/B6*C6,C6)',
    sourceDataSheets: ['Procurement Scorecard', '7 TMPS '],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: null,
  },
  {
    indicatorKey: 'preferential_procurement.eme',
    displayName: 'Procurement — EME suppliers',
    workbookSheet: 'Procurement Scorecard',
    workbookCells: { target: 'B7', availablePoints: 'C7', achievedPercentage: 'D7', pointsAchieved: 'E7' },
    target: 0.15,
    targetLabel: '15% of TMPS',
    basePoints: 4,
    bonusPoints: 0,
    numerator: "'7 TMPS '!H15",
    denominator: "'7 TMPS '!G10",
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D7/B7*C7,C7)',
    sourceDataSheets: ['Procurement Scorecard', '7 TMPS '],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: null,
  },
  {
    indicatorKey: 'preferential_procurement.black_owned_51',
    displayName: 'Procurement — at least 51% black-owned suppliers',
    workbookSheet: 'Procurement Scorecard',
    workbookCells: { target: 'B8', availablePoints: 'C8', achievedPercentage: 'D8', pointsAchieved: 'E8' },
    target: 0.5,
    targetLabel: '50% of TMPS',
    basePoints: 11,
    bonusPoints: 0,
    numerator: "'7 TMPS '!I15",
    denominator: "'7 TMPS '!G10",
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D8/B8*C8,C8)',
    sourceDataSheets: ['Procurement Scorecard', '7 TMPS '],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: null,
  },
  {
    indicatorKey: 'preferential_procurement.black_women_owned_30',
    displayName: 'Procurement — at least 30% black-women-owned suppliers',
    workbookSheet: 'Procurement Scorecard',
    workbookCells: { target: 'B9', availablePoints: 'C9', achievedPercentage: 'D9', pointsAchieved: 'E9' },
    target: 0.12,
    targetLabel: '12% of TMPS',
    basePoints: 4,
    bonusPoints: 0,
    numerator: "'7 TMPS '!J15",
    denominator: "'7 TMPS '!G10",
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D9/B9*C9,C9)',
    sourceDataSheets: ['Procurement Scorecard', '7 TMPS '],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: null,
  },
  {
    indicatorKey: 'preferential_procurement.bonus.designated_group',
    displayName: 'Procurement bonus — designated group suppliers',
    workbookSheet: 'Procurement Scorecard',
    workbookCells: { target: 'B11', availablePoints: 'C11', achievedPercentage: 'D11', pointsAchieved: 'E11' },
    target: 0.02,
    targetLabel: '2% of TMPS',
    basePoints: 0,
    bonusPoints: 2,
    numerator: "'7 TMPS '!K15",
    denominator: "'7 TMPS '!G10",
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D11/B11*C11,C11)',
    sourceDataSheets: ['Procurement Scorecard', '7 TMPS '],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect: null,
  },
  {
    indicatorKey: null,
    displayName: 'Preferential Procurement total',
    workbookSheet: 'Procurement Scorecard',
    workbookCells: { availablePoints: 'C12', pointsAchieved: 'E12' },
    target: null,
    targetLabel: 'n/a',
    basePoints: 27,
    bonusPoints: 2,
    numerator: 'Sum of procurement indicators',
    denominator: 'n/a',
    cap: null,
    workbookFormula: 'C12 = SUM(C5:C9) = 27; E12 = SUM(E5:E9,E11)',
    sourceDataSheets: ['Procurement Scorecard'],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'Available points (27) exclude the bonus while achieved points (E12) include it. The engine reports base and bonus separately.',
  },
  {
    indicatorKey: null,
    displayName: 'Procurement demonstration supplier row',
    workbookSheet: 'Procurement Scorecard',
    workbookCells: { numerator: 'A16:AB16', denominator: 'O14:X14' },
    target: null,
    targetLabel: 'n/a',
    basePoints: 0,
    bonusPoints: 0,
    numerator: 'One demonstration supplier producing R5 000 000 TMPS and R8 100 000 recognised spend',
    denominator: 'n/a',
    cap: null,
    workbookFormula: 'SUM(O16:O1048576) and siblings',
    sourceDataSheets: ['Procurement Scorecard'],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'not_a_scoring_rule',
    workbookParityStatus: 'excluded_demonstration_data',
    knownWorkbookDefect:
      'Recognised spend (8.1m) exceeds TMPS (5m), producing a 162% achievement and full marks on four procurement rows. Never import as client data.',
  },

  // ------------------------------------------- Enterprise / Supplier Development
  {
    indicatorKey: 'enterprise_development.contributions',
    displayName: 'Enterprise Development contributions',
    workbookSheet: 'ED & SD',
    workbookCells: {
      target: 'B5',
      availablePoints: 'C5',
      achievedPercentage: 'D5',
      pointsAchieved: 'E5',
      numerator: 'C39',
      denominator: 'B19',
    },
    target: 0.01,
    targetLabel: '1% of NPAT',
    basePoints: 5,
    bonusPoints: 0,
    numerator: 'SUM(C25:C38) — beneficiary contribution amounts',
    denominator: "'NPAT Calculation'!B27",
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D5/B5*C5,C5) where D5 = C39/B19',
    sourceDataSheets: ['ED & SD', 'NPAT Calculation'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'replaced_with_official_rule',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'Treats every raw contribution amount as 100% recognised — there is no benefit-factor column, so loans, guarantees and professional services would be over-recognised. Inherits the broken NPAT denominator.',
  },
  {
    indicatorKey: 'supplier_development.contributions',
    displayName: 'Supplier Development contributions',
    workbookSheet: 'ED & SD',
    workbookCells: {
      target: 'B8',
      availablePoints: 'C8',
      achievedPercentage: 'D8',
      pointsAchieved: 'E8',
      numerator: 'C60',
      denominator: 'B19',
    },
    target: 0.02,
    targetLabel: '2% of NPAT',
    basePoints: 10,
    bonusPoints: 0,
    numerator: 'SUM(C45:C59) — beneficiary contribution amounts',
    denominator: "'NPAT Calculation'!B27",
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D8/B8*C8,C8) where D8 = C60/B19',
    sourceDataSheets: ['ED & SD', 'NPAT Calculation'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'replaced_with_official_rule',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'No benefit-factor column; inherits the broken NPAT denominator.',
  },
  {
    indicatorKey: 'enterprise_development.bonus.job_creation',
    displayName: 'ESD bonus — job creation',
    workbookSheet: 'ED & SD',
    workbookCells: { target: 'B11', availablePoints: 'C11' },
    target: 1,
    targetLabel: 'Yes / No',
    basePoints: 0,
    bonusPoints: 1,
    numerator: 'Manual yes/no',
    denominator: 'n/a',
    cap: '1 point',
    workbookFormula: null,
    sourceDataSheets: ['ED & SD'],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'The workbook has no achieved cell for this row on the ED & SD sheet, so the bonus can never be earned there; the Full Scorecard sheet carries a separate manual "No" at D64.',
  },
  {
    indicatorKey: 'supplier_development.bonus.graduation',
    displayName: 'ESD bonus — graduation from ED to SD',
    workbookSheet: 'ED & SD',
    workbookCells: { target: 'B13', availablePoints: 'C13' },
    target: 1,
    targetLabel: 'Yes / No',
    basePoints: 0,
    bonusPoints: 1,
    numerator: 'Manual yes/no',
    denominator: 'n/a',
    cap: '1 point',
    workbookFormula: null,
    sourceDataSheets: ['ED & SD'],
    missingInputBehaviour: 'score_zero',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect: 'Same missing achieved cell as job creation.',
  },
  {
    indicatorKey: null,
    displayName: '"11% more new jobs created as a result of ESD initiatives"',
    workbookSheet: 'ED & SD',
    workbookCells: { target: 'B15', availablePoints: 'C15' },
    target: 0.11,
    targetLabel: 'Yes / No',
    basePoints: 0,
    bonusPoints: 2,
    numerator: 'Manual yes/no',
    denominator: 'n/a',
    cap: '2 points',
    workbookFormula: null,
    sourceDataSheets: ['ED & SD'],
    missingInputBehaviour: 'blocked_pending_confirmation',
    officialRuleStatus: 'requires_reap_confirmation',
    workbookParityStatus: 'unsupported_or_orphaned',
    knownWorkbookDefect:
      'Not referenced by the sheet total (E17 sums E5, E8, E11 and E13 only) and has no equivalent in Statement 400. Excluded until REAP confirms it.',
  },
  {
    indicatorKey: null,
    displayName: 'ED & SD element total',
    workbookSheet: 'ED & SD',
    workbookCells: { availablePoints: 'C17', pointsAchieved: 'E17' },
    target: null,
    targetLabel: 'n/a',
    basePoints: 15,
    bonusPoints: 2,
    numerator: 'ED + SD points',
    denominator: 'n/a',
    cap: null,
    workbookFormula: "C17 = 'Procurement Scorecard'!E12+'ED & SD'!C5:C6+'ED & SD'!C8:C9",
    sourceDataSheets: ['ED & SD', 'Procurement Scorecard'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'not_a_scoring_rule',
    workbookParityStatus: 'unsupported_or_orphaned',
    knownWorkbookDefect:
      'Available points are computed from the procurement points ACHIEVED (Procurement Scorecard!E12) rather than the procurement points AVAILABLE, so the denominator moves as the client scores. C18 then hard-codes 20 as an unexplained override.',
  },

  // --------------------------------------------------------------------- SED
  {
    indicatorKey: 'socio_economic_development.contributions',
    displayName: 'Socio-Economic Development contributions',
    workbookSheet: 'SED',
    workbookCells: {
      target: 'B5',
      availablePoints: 'C5',
      achievedPercentage: 'D5',
      pointsAchieved: 'E5',
      numerator: 'C28',
      denominator: 'B9',
    },
    target: 0.01,
    targetLabel: '1% of NPAT',
    basePoints: 5,
    bonusPoints: 0,
    numerator: 'SUM(C13:C27) — recognised amounts',
    denominator: "'NPAT Calculation'!B27",
    cap: CAP_PROPORTIONAL,
    workbookFormula: 'MIN(D5/B5*C5,C5) where D5 = C28/B9',
    sourceDataSheets: ['SED', 'NPAT Calculation'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'exact_parity',
    knownWorkbookDefect:
      'Inherits the broken NPAT denominator. The "Claimed" column (B12) is captured but never used in any formula.',
  },
  {
    indicatorKey: null,
    displayName: 'SED "Claimed" column',
    workbookSheet: 'SED',
    workbookCells: { numerator: 'B12' },
    target: null,
    targetLabel: 'n/a',
    basePoints: 0,
    bonusPoints: 0,
    numerator: 'Claimed amount per beneficiary',
    denominator: 'n/a',
    cap: null,
    workbookFormula: null,
    sourceDataSheets: ['SED'],
    missingInputBehaviour: 'blocked_pending_confirmation',
    officialRuleStatus: 'requires_reap_confirmation',
    workbookParityStatus: 'requires_reap_confirmation',
    knownWorkbookDefect:
      'Column header exists with no formula, no total and no definition. Preserved as an optional raw input; excluded from scoring until REAP defines it.',
  },

  // ---------------------------------------------------------- NPAT and totals
  {
    indicatorKey: null,
    displayName: 'Applicable NPAT denominator',
    workbookSheet: 'NPAT Calculation',
    workbookCells: { numerator: 'B21', denominator: 'B23', pointsAchieved: 'B27' },
    target: null,
    targetLabel: 'Greater of actual NPAT and deemed NPAT',
    basePoints: 0,
    bonusPoints: 0,
    numerator: 'Deemed NPAT = revenue × (industry NPAT margin × 25%)',
    denominator: 'Actual NPAT',
    cap: null,
    workbookFormula: 'B27 = B23',
    sourceDataSheets: ['NPAT Calculation'],
    missingInputBehaviour: 'blocked_pending_confirmation',
    officialRuleStatus: 'replaced_with_official_rule',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'A25 instructs "Apply the greater of the two for calculation purposes" but B27 simply returns actual NPAT, so deemed NPAT is computed and then discarded. Every ED, SD and SED target inherits this.',
  },
  {
    indicatorKey: null,
    displayName: 'Scorecard total',
    workbookSheet: 'Full Scorecard',
    workbookCells: { availablePoints: 'C70', pointsAchieved: 'E70' },
    target: null,
    targetLabel: 'n/a',
    basePoints: 111,
    bonusPoints: 9,
    numerator: 'Sum of element totals',
    denominator: 'n/a',
    cap: null,
    workbookFormula: 'C70 = SUM(C14,C36,C46,C66,C69) = 111; E70 = E36+E46+E66+E69+E14',
    sourceDataSheets: ['Full Scorecard'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'C66 sums 42 available points for the ESD pillar while E66 adds the designated-group, job-creation and graduation bonus points, so the 111 total mixes base-only availability with base-plus-bonus achievement.',
  },
  {
    indicatorKey: null,
    displayName: 'B-BBEE level table',
    workbookSheet: 'Summary ',
    workbookCells: { numerator: 'G2:I11' },
    target: null,
    targetLabel: 'n/a',
    basePoints: 0,
    bonusPoints: 0,
    numerator: 'Static lookup table of levels and recognition percentages',
    denominator: 'n/a',
    cap: null,
    workbookFormula: null,
    sourceDataSheets: ['Summary '],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'matches_official_source',
    workbookParityStatus: 'corrected_workbook_defect',
    knownWorkbookDefect:
      'The table is printed but never applied: no formula maps the scorecard total (C10) to a level, and there is no priority-element sub-minimum test or one-level discount anywhere in the workbook.',
  },
  {
    indicatorKey: null,
    displayName: 'Priority element sub-minimum summary',
    workbookSheet: ' Yes Targets Calc',
    workbookCells: { availablePoints: 'H5:M5', pointsAchieved: 'H6:M6', achievedPercentage: 'I3' },
    target: 0.4,
    targetLabel: '40%',
    basePoints: 0,
    bonusPoints: 0,
    numerator: 'Ownership 8 + Skills 20 + Procurement 27 + SD 10 + ED 5 = 70',
    denominator: 'n/a',
    cap: null,
    workbookFormula: 'I3 = M6/M5',
    sourceDataSheets: [' Yes Targets Calc'],
    missingInputBehaviour: 'no_score_needs_review',
    officialRuleStatus: 'requires_reap_confirmation',
    workbookParityStatus: 'unsupported_or_orphaned',
    knownWorkbookDefect:
      'Computes a single average across all five priority measures instead of testing each against its own 40% threshold, uses 27 rather than the gazetted 25-point basis for procurement, caches an error, and feeds nothing.',
  },
]

export const WORKBOOK_REFERENCE = {
  fileName: 'Generic-Scorecard Calculator.xlsx',
  sha256: '93494e2916e21ad88072a074edadc75d351db6f28c10222463df8de641168fc0',
  sizeBytes: 342606,
  worksheetCount: 22,
  formulaCount: 633,
  cachedErrorCellCount: 205,
  hiddenSheetCount: 0,
  macrosPresent: false,
  externalWorkbookLinks: 0,
} as const

export function workbookRulesForIndicator(indicatorKey: string): WorkbookRuleRecord[] {
  return WORKBOOK_RULE_INVENTORY.filter((record) => record.indicatorKey === indicatorKey)
}

export function workbookRulesByParityStatus(status: WorkbookParityStatus): WorkbookRuleRecord[] {
  return WORKBOOK_RULE_INVENTORY.filter((record) => record.workbookParityStatus === status)
}
