import type { Guide } from './types'

export const companiesGuide: Guide = {
  id: 'companies',
  title: 'Companies guide',
  description: 'Add companies, browse your directory, and start procurement work from a client profile.',
  estimatedMinutes: 2,
  routePrefixes: ['/companies'],
  steps: [
    {
      id: 'companies-intro',
      phase: 'Companies',
      title: 'Your company directory',
      body: 'Companies are the foundation of REAP Scorecard. Every scorecard and procurement assessment is linked to a client organisation.',
      target: 'companies-header',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/companies',
    },
    {
      id: 'companies-new',
      phase: 'Create',
      title: 'Add a new company',
      body: 'Click New Company to register a client organisation with contact details and industry information.',
      hint: 'Click the button to continue.',
      target: 'companies-new',
      placement: 'bottom',
      mode: 'action',
      advanceOn: 'navigate',
      requiredPath: '/companies',
    },
    {
      id: 'company-form',
      phase: 'Create',
      title: 'Company details form',
      body: 'Enter the legal or trading name, contact person, email, and phone. Save when complete.',
      target: 'company-form',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/companies/new',
    },
    {
      id: 'company-workspace',
      phase: 'Workspace',
      title: 'Company workspace',
      body: 'From a company profile you can view procurement assessments, stats, and start new work for this client.',
      target: 'company-workspace',
      placement: 'bottom',
      mode: 'info',
    },
    {
      id: 'company-procurement',
      phase: 'Procurement',
      title: 'Start a procurement assessment',
      body: 'Click New Procurement Assessment to capture supplier data, TMPS, and calculate procurement points for this company.',
      hint: 'Click the button to open the assessment workspace.',
      target: 'company-procurement-new',
      placement: 'left',
      mode: 'action',
      advanceOn: 'navigate',
    },
    {
      id: 'finish',
      phase: 'Complete',
      title: 'Companies guide complete',
      body: 'You know how to add companies and start procurement work. Use Need help? anytime for other guides.',
      placement: 'center',
      mode: 'info',
    },
  ],
}
