import type { Guide } from './types'

export const firstTimeSetupGuide: Guide = {
  id: 'first-time-setup',
  title: 'First-time setup',
  description: 'Complete your checklist step by step — click each highlighted action to continue.',
  estimatedMinutes: 3,
  routePrefixes: ['/dashboard'],
  steps: [
    {
      id: 'welcome',
      phase: 'Start here',
      title: 'Let\'s get you set up',
      body: 'This guide walks you through the three setup steps on your dashboard. You\'ll click the real buttons — we\'ll highlight exactly where to go.',
      hint: 'Takes about three minutes. Press Escape anytime to exit.',
      placement: 'center',
      mode: 'info',
    },
    {
      id: 'checklist-overview',
      phase: 'Setup',
      title: 'Your setup checklist',
      body: 'These three steps unlock the full workspace: add a company, run a procurement assessment, then review activity.',
      target: 'setup-checklist',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/dashboard',
    },
    {
      id: 'create-company',
      phase: 'Step 1',
      title: 'Create your first company',
      body: 'Click the button below to add an organisation profile. Every procurement assessment is linked to a company.',
      hint: 'Click "Create a company" to continue.',
      target: 'checklist-create-company',
      fallbackTargets: ['nav-companies-new'],
      placement: 'top',
      mode: 'action',
      advanceOn: 'navigate',
      requiredPath: '/dashboard',
    },
    {
      id: 'company-form',
      phase: 'Step 1',
      title: 'Enter company details',
      body: 'Fill in the company name and contact details. Required fields are marked with an asterisk.',
      hint: 'When you\'re ready, click Save company at the bottom.',
      target: 'company-form',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/companies/new',
    },
    {
      id: 'save-company',
      phase: 'Step 1',
      title: 'Save your company',
      body: 'Click Save company to create the profile. You\'ll be taken to the company workspace.',
      hint: 'Click the Save button to continue.',
      target: 'company-form-save',
      placement: 'top',
      mode: 'action',
      advanceOn: 'navigate',
      requiredPath: '/companies/new',
    },
    {
      id: 'company-created',
      phase: 'Step 1 complete',
      title: 'Company created',
      body: 'Great work — your first company is ready. Head back to the dashboard for step 2: run your first procurement assessment.',
      hint: 'Click Dashboard in the sidebar to continue.',
      target: 'nav-dashboard',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'action',
      advanceOn: 'navigate',
    },
    {
      id: 'new-scorecard',
      phase: 'Step 2',
      title: 'Run your first procurement assessment',
      body: 'Click New procurement assessment to select a company, capture supplier data, and calculate procurement points.',
      hint: 'Click the button to continue.',
      target: 'checklist-new-scorecard',
      fallbackTargets: ['new-scorecard'],
      placement: 'top',
      mode: 'action',
      advanceOn: 'navigate',
      requiredPath: '/dashboard',
    },
    {
      id: 'scorecard-intro',
      phase: 'Step 2',
      title: 'Procurement workspace',
      body: 'Confirm the assessment year and TMPS denominator, import or add supplier rows, then save. You can return here anytime from Companies.',
      placement: 'center',
      mode: 'info',
    },
    {
      id: 'back-to-dashboard',
      phase: 'Step 3',
      title: 'Return to dashboard',
      body: 'Once your assessment is saved (or when you\'re ready), go back to the dashboard for the final setup step.',
      hint: 'Click Dashboard in the sidebar.',
      target: 'nav-dashboard',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'action',
      advanceOn: 'navigate',
    },
    {
      id: 'open-activity',
      phase: 'Step 3',
      title: 'Review activity',
      body: 'Click Open Activity to see your audit trail — every company and assessment change is recorded here.',
      hint: 'Click "Open Activity" to continue.',
      target: 'checklist-activity',
      fallbackTargets: ['nav-activity'],
      placement: 'top',
      mode: 'action',
      advanceOn: 'navigate',
      requiredPath: '/dashboard',
    },
    {
      id: 'activity-intro',
      phase: 'Step 3',
      title: 'Your audit trail',
      body: 'Activity shows who changed what and when. Use it to trace updates across companies and procurement assessments.',
      target: 'activity-main',
      fallbackTargets: ['nav-activity'],
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/dashboard/activity',
    },
    {
      id: 'finish',
      phase: 'Complete',
      title: 'Setup complete',
      body: 'You\'ve finished the essentials. Open Companies for client work, run procurement assessments, and export PDFs when you\'re ready to share results.',
      hint: 'Restart any guide from Need help? in the top bar.',
      placement: 'center',
      mode: 'info',
    },
  ],
}
