import type { Guide } from './types'

export const firstTimeSetupGuide: Guide = {
  id: 'first-time-setup',
  title: 'First-time setup',
  description: 'Complete your checklist step by step — click each highlighted action to continue.',
  estimatedMinutes: 3,
  routePrefixes: ['/dashboard'],
  steps: [
    {
      id: 'welcome',
      phase: 'Start here',
      title: 'Let\'s get you set up',
      body: 'This guide walks you through three first steps: add a company, start an assessment, and see your activity. You click the real buttons; we highlight where.',
      hint: 'Takes about three minutes. Press Escape anytime to exit.',
      placement: 'center',
      mode: 'info',
    },
    {
      id: 'checklist-overview',
      phase: 'Setup',
      title: 'Your setup checklist',
      body: 'These three steps unlock the full workspace: add a company, run a procurement assessment, then review activity.',
      target: 'setup-checklist',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/dashboard',
    },
    {
      id: 'create-company',
      phase: 'Step 1',
      title: 'Create your first company',
      body: 'Click the button below to add an organisation profile. Every procurement assessment is linked to a company.',
      hint: 'Click "Create a company" to continue.',
      target: 'checklist-create-company',
      fallbackTargets: ['nav-companies-new'],
      placement: 'top',
      mode: 'action',
      advanceOn: 'navigate',
      requiredPath: '/dashboard',
    },
    {
      id: 'company-form',
      phase: 'Step 1',
      title: 'Enter company details',
      body: 'Only the company name is required. Everything else can be added later. Click Save company when you are ready, or skip the guide at any time.',
      hint: 'Type freely, then click Save company. Press Escape to skip the guide.',
      placement: 'center',
      mode: 'info',
      requiredPath: '/companies/new',
    },
    {
      id: 'save-company',
      phase: 'Step 1',
      title: 'Save your company',
      body: 'Click Save company to create the profile. You\'ll be taken to the company workspace.',
      hint: 'The Save button is highlighted and clickable.',
      target: 'company-form-save',
      placement: 'top',
      mode: 'action',
      advanceOn: 'navigate',
      requiredPath: '/companies/new',
    },
    {
      id: 'company-created',
      phase: 'Step 1 complete',
      title: 'Company created',
      body: 'Your first company is ready. Go back to Home for step 2: start your first assessment.',
      hint: 'Click Home in the menu to continue.',
      target: 'nav-dashboard',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'action',
      advanceOn: 'navigate',
    },
    {
      id: 'new-scorecard',
      phase: 'Step 2',
      title: 'Start your first assessment',
      body: 'Click Start new. Choose a full B-BBEE scorecard for a final level, or procurement only for just the procurement points.',
      hint: 'Click Start new to continue.',
      target: 'new-scorecard',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'action',
      advanceOn: 'navigate',
      requiredPath: '/dashboard',
    },
    {
      id: 'scorecard-intro',
      phase: 'Step 2',
      title: 'Procurement workspace',
      body: 'Follow the steps shown at the top of the page. You can come back to this assessment any time from Home or Companies.',
      placement: 'center',
      mode: 'info',
    },
    {
      id: 'back-to-dashboard',
      phase: 'Step 3',
      title: 'Back to Home',
      body: 'Once your assessment is saved (or when you\'re ready), go back to Home for the last step.',
      hint: 'Click Home in the menu.',
      target: 'nav-dashboard',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'action',
      advanceOn: 'navigate',
    },
    {
      id: 'open-activity',
      phase: 'Step 3',
      title: 'Review activity',
      body: 'Click See all activity to see every change to your companies and assessments.',
      hint: 'Click See all activity to continue.',
      target: 'checklist-activity',
      fallbackTargets: ['nav-activity'],
      placement: 'top',
      mode: 'action',
      advanceOn: 'navigate',
      requiredPath: '/dashboard',
    },
    {
      id: 'activity-intro',
      phase: 'Step 3',
      title: 'Your audit trail',
      body: 'Activity shows who changed what and when. Use it to trace updates across companies and procurement assessments.',
      target: 'activity-main',
      fallbackTargets: ['nav-activity'],
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/dashboard/activity',
    },
    {
      id: 'finish',
      phase: 'Complete',
      title: 'Setup complete',
      body: 'You\'ve finished the essentials. Open Companies for client work, run procurement assessments, and export PDFs when you\'re ready to share results.',
      hint: 'Restart any guide from Need help? in the top bar.',
      placement: 'center',
      mode: 'info',
    },
  ],
}
