import type { Guide } from './types'

export const fullPlatformGuide: Guide = {
  id: 'full-platform',
  title: 'Full platform tour',
  description: 'A complete walkthrough of navigation, setup, procurement, and export.',
  estimatedMinutes: 4,
  steps: [
    {
      id: 'welcome',
      phase: 'Start here',
      title: 'Welcome to REAP Scorecard',
      body: 'This guide walks you through the platform — where to find everything, how to complete your setup checklist, and how to run a procurement scorecard from start to export.',
      hint: 'Takes about four minutes. You can skip or restart anytime from Need help? in the top bar.',
      placement: 'center',
      mode: 'info',
    },
    {
      id: 'dashboard',
      phase: 'Orientation',
      title: 'Your dashboard',
      body: 'This is your home screen. It shows your setup progress, portfolio metrics, and recent scorecard activity as you add companies and assessments.',
      target: 'dashboard',
      fallbackTargets: ['dashboard-main'],
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/dashboard',
    },
    {
      id: 'setup-checklist',
      phase: 'Setup',
      title: 'Complete your setup checklist',
      body: 'Work through these three steps in order: add a company, run a procurement assessment, then review activity.',
      hint: 'Step 1 — Create a company. Step 2 — New procurement assessment. Step 3 — Track changes in Activity.',
      target: 'setup-checklist',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/dashboard',
    },
    {
      id: 'sidebar',
      phase: 'Navigation',
      title: 'Sidebar navigation',
      body: 'The sidebar is always available on desktop. Use Main for overview pages, Create for new records, and Settings for your profile.',
      target: 'sidebar-nav',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'info',
    },
    {
      id: 'companies',
      phase: 'Navigation',
      title: 'Companies and scorecards',
      body: 'Every procurement assessment belongs to a company. Open Companies to view client profiles, past assessments, and start new work.',
      target: 'scorecards',
      fallbackTargets: ['nav-companies', 'mobile-guide'],
      placement: 'right',
      mode: 'action',
      advanceOn: 'navigate',
    },
    {
      id: 'create-menu',
      phase: 'Create',
      title: 'Create menu',
      body: 'Use Create when you already know what you need: a new company profile, a procurement assessment, or a full scorecard workbook upload.',
      target: 'sidebar-create',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'info',
    },
    {
      id: 'procurement-entry',
      phase: 'Procurement',
      title: 'Procurement scorecard entry point',
      body: 'New Procurement Assessment is the main path to the procurement scorecard. Select a company first, then capture supplier data, TMPS, and points.',
      hint: 'Recommended flow: Companies → open a company → New Procurement Assessment.',
      target: 'new-scorecard',
      fallbackTargets: ['scorecard-nav', 'mobile-guide'],
      placement: 'right',
      mode: 'info',
    },
    {
      id: 'after-setup',
      phase: 'Next steps',
      title: 'What to do after setup',
      body: 'Once your checklist is complete, move into live client work: open Companies, choose a client, and start a procurement assessment. Use Activity to review changes and Download PDF when you are ready to share results.',
      hint: 'Stuck after setup? Start at Companies, pick a client, then New Procurement Assessment.',
      placement: 'center',
      mode: 'info',
    },
    {
      id: 'activity',
      phase: 'Governance',
      title: 'Activity audit trail',
      body: 'Activity records company and scorecard changes over time. Use it to review who did what and when — especially useful after your initial setup.',
      target: 'nav-activity',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'info',
    },
    {
      id: 'workspace',
      phase: 'Procurement workflow',
      title: 'Scorecard workspace',
      body: 'This is the procurement assessment workspace — where supplier data is captured, TMPS is confirmed, and the score is calculated for a specific company.',
      target: 'scorecard-workspace',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/procurement',
    },
    {
      id: 'inputs',
      phase: 'Procurement workflow',
      title: 'Capture procurement inputs',
      body: 'Enter the assessment year, choose your TMPS denominator, import or add supplier rows, and confirm the live preview before saving.',
      target: 'scorecard-inputs',
      placement: 'top',
      mode: 'info',
      requiredPath: '/procurement',
    },
    {
      id: 'results',
      phase: 'Procurement workflow',
      title: 'Review score results',
      body: 'After saving, the system displays procurement points, REAP level, category breakdown, and recognised spend in this summary section.',
      target: 'results',
      fallbackTargets: ['scorecard-results'],
      placement: 'top',
      mode: 'info',
      requiredPath: '/procurement',
    },
    {
      id: 'export',
      phase: 'Reporting',
      title: 'Export and share',
      body: 'Download a client-ready PDF or open the full report view. Use this when presenting results to clients or internal stakeholders.',
      target: 'reports',
      fallbackTargets: ['scorecard-export'],
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/procurement/assessments',
    },
    {
      id: 'finish',
      phase: 'Complete',
      title: 'You are ready to work',
      body: 'You now know where to find the dashboard, complete setup, open companies, run procurement assessments, and export results. Restart this guide anytime from Need help? in the top bar.',
      hint: 'Your data is never changed by this guide — it only shows you where to click.',
      placement: 'center',
      mode: 'info',
    },
  ],
}
