import type { Guide } from './types'

export const fullPlatformGuide: Guide = {
  id: 'full-platform',
  title: 'Full platform tour',
  description: 'Where everything is: home, starting a scorecard, companies, procurement, and reports.',
  estimatedMinutes: 4,
  steps: [
    {
      id: 'welcome',
      phase: 'Start here',
      title: 'Welcome to REAP Scorecard',
      body: 'This guide shows you where everything is: your home screen, how to start a full scorecard or a procurement-only assessment, and where to find your reports.',
      hint: 'Takes about four minutes. You can skip it, or restart it any time from Help.',
      placement: 'center',
      mode: 'info',
    },
    {
      id: 'dashboard',
      phase: 'Orientation',
      title: 'Your home screen',
      body: 'Home shows your companies, how far each assessment has got, and the one thing to do next.',
      target: 'dashboard',
      fallbackTargets: ['dashboard-main'],
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/dashboard',
    },
    {
      id: 'setup-checklist',
      phase: 'Setup',
      title: 'The next thing to do',
      body: 'This box always shows the single most useful next step, such as adding your first company or finishing an assessment.',
      hint: 'Click its button whenever you are not sure what to do next.',
      target: 'setup-checklist',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/dashboard',
    },
    {
      id: 'sidebar',
      phase: 'Navigation',
      title: 'Finding your way around',
      body: 'The menu has the same five places on every page: Home, Companies, Full scorecards, Procurement and Settings. On a phone, open it with the Menu button.',
      target: 'sidebar-nav',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'info',
    },
    {
      id: 'companies',
      phase: 'Navigation',
      title: 'Companies',
      body: 'Every assessment belongs to a company. Open Companies to see each client and all of their assessments in one place.',
      target: 'nav-companies',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'info',
    },
    {
      id: 'create-menu',
      phase: 'Create',
      title: 'Start something new',
      body: 'Start new is the one starting point. It offers a full B-BBEE scorecard (all elements and a final level) or a procurement-only assessment (just the procurement points).',
      target: 'new-scorecard',
      fallbackTargets: ['mobile-guide'],
      placement: 'right',
      mode: 'info',
    },
    {
      id: 'procurement-entry',
      phase: 'Procurement',
      title: 'Full scorecards and procurement',
      body: 'Full scorecards lists every full B-BBEE assessment. Procurement lists every procurement-only assessment. A procurement assessment can also be attached to a full scorecard.',
      target: 'nav-scorecards',
      fallbackTargets: ['nav-procurement', 'mobile-guide'],
      placement: 'right',
      mode: 'info',
    },
    {
      id: 'after-setup',
      phase: 'Next steps',
      title: 'A typical piece of work',
      body: 'Click Start new, choose full scorecard or procurement only, pick the company, then follow the steps shown at the top of each page. When it is calculated, open the report to print or save it as a PDF.',
      hint: 'The steps bar at the top of each assessment page always shows where you are.',
      placement: 'center',
      mode: 'info',
    },
    {
      id: 'activity',
      phase: 'Governance',
      title: 'Activity',
      body: 'Activity records every change to companies and assessments: who did what, and when.',
      target: 'checklist-activity',
      placement: 'top',
      mode: 'info',
      requiredPath: '/dashboard',
    },
    {
      id: 'workspace',
      phase: 'Procurement workflow',
      title: 'Scorecard workspace',
      body: 'This is the procurement assessment workspace — where supplier data is captured, TMPS is confirmed, and the score is calculated for a specific company.',
      target: 'scorecard-workspace',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/procurement',
    },
    {
      id: 'inputs',
      phase: 'Procurement workflow',
      title: 'Capture procurement inputs',
      body: 'Enter the assessment year, choose your TMPS denominator, import or add supplier rows, and confirm the live preview before saving.',
      target: 'scorecard-inputs',
      placement: 'top',
      mode: 'info',
      requiredPath: '/procurement',
    },
    {
      id: 'results',
      phase: 'Procurement workflow',
      title: 'Review score results',
      body: 'After saving, the system displays procurement points, REAP level, category breakdown, and recognised spend in this summary section.',
      target: 'results',
      fallbackTargets: ['scorecard-results'],
      placement: 'top',
      mode: 'info',
      requiredPath: '/procurement',
    },
    {
      id: 'export',
      phase: 'Reporting',
      title: 'Export and share',
      body: 'Download a client-ready PDF or open the full report view. Use this when presenting results to clients or internal stakeholders.',
      target: 'reports',
      fallbackTargets: ['scorecard-export'],
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/procurement/assessments',
    },
    {
      id: 'finish',
      phase: 'Complete',
      title: 'You are ready to work',
      body: 'You now know where home is, how to start a full scorecard or a procurement assessment, and where to find reports. Restart this guide any time from Help.',
      hint: 'This guide never changes your data. It only shows you where to click.',
      placement: 'center',
      mode: 'info',
    },
  ],
}
