import type { Guide } from './types'

export const procurementGuide: Guide = {
  id: 'procurement',
  title: 'Procurement scorecard guide',
  description: 'Walk through the procurement assessment workspace from inputs to results.',
  estimatedMinutes: 3,
  routePrefixes: ['/procurement'],
  steps: [
    {
      id: 'workspace-intro',
      phase: 'Workspace',
      title: 'Procurement assessment workspace',
      body: 'This is where you capture supplier data, confirm TMPS, and calculate procurement points for a specific company and assessment year.',
      target: 'scorecard-workspace',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/procurement',
    },
    {
      id: 'inputs',
      phase: 'Capture',
      title: 'Enter procurement inputs',
      body: 'Set the assessment year, choose your TMPS denominator, then import or manually add supplier rows. The live preview updates as you work.',
      target: 'scorecard-inputs',
      placement: 'top',
      mode: 'info',
      requiredPath: '/procurement',
    },
    {
      id: 'save-hint',
      phase: 'Capture',
      title: 'Save your assessment',
      body: 'When inputs are complete, save the assessment. The system calculates procurement points, REAP level, and recognised spend automatically.',
      hint: 'Look for the Save button at the bottom of the form.',
      placement: 'center',
      mode: 'info',
      requiredPath: '/procurement/assessments/new',
    },
    {
      id: 'results',
      phase: 'Results',
      title: 'Review score results',
      body: 'After saving, this section shows procurement points, REAP level, category breakdown, and recognised spend.',
      target: 'scorecard-results',
      placement: 'top',
      mode: 'info',
      requiredPath: '/procurement',
    },
    {
      id: 'export-hint',
      phase: 'Export',
      title: 'Export when ready',
      body: 'On a saved assessment, use Download PDF to generate a client-ready report. Start the Export guide from Need help? for a full walkthrough.',
      target: 'scorecard-export',
      placement: 'bottom',
      mode: 'info',
      requiredPath: '/procurement/assessments',
    },
    {
      id: 'finish',
      phase: 'Complete',
      title: 'Procurement guide complete',
      body: 'You know how to run a procurement assessment end to end. Restart this guide anytime from Need help?.',
      placement: 'center',
      mode: 'info',
    },
  ],
}
